"""add_auth_fields_to_users

Revision ID: 9f5dabb64afa
Revises: 10edba2f92ae
Create Date: 2026-06-16 14:06:55.758801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5dabb64afa'
down_revision: Union[str, Sequence[str], None] = '10edba2f92ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('provider_user_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider_user_id')
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
